title: Muhammad Naveed
description:  Seasoned IT Professional, passionate about solving business problems with technology. <br>Hands on, with experience in successfully delivering large enterprise programs.
show_downloads: true
google_analytics: G-Z5YQCY7KR6
theme: jekyll-theme-cayman